---
# handlers file for mysql
- name: Enable mysql service
  ansible.builtin.service:
    name: mysql
    enabled: true

- name: Start mysql service
  ansible.builtin.service:
    name: mysql
    state: started

- name: Restart MySQL Service
  ansible.builtin.service:
    name: mysql
    state: restarted