FROM nginx:latest
# If you do not specify a tag , by deafult it consider as latest tag.

COPY index.html /usr/share/nginx/html/

EXPOSE 80

# I dyou use nginx image , then you dont need to start service of nginx.