---
# tasks file for kubeadm
- name: update system repo
  apt:
    update_cache: true

- name: Disable swap
  become: true
  command: swapoff -a
  # update_cache: true

- name: copy conf file for bootup
  ansible.builtin.copy:
    src: k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: load k8s.conf file
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: create /etc/sysctl.d directory
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory

- name: configure sysctl parameters
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: Apply sysctl
  command: sudo sysctl --system

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: true

- name: create directory /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: create /etc/containerd/config.toml file
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: touch
  
- name: config containerd
  command: containerd config default | sudo tee /etc/containerd/config.toml

- name: Modify containerd config to enable systemd
  command: sed -i "s/SystemdCgroup = false/SystemdCgroup = true/g" /etc/containerd/config.toml 
  notify: restart containerd

- name: install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gpg

- name: create /etc/apt/keyrings directory to install repo 
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- name: Download Kubernetes APT key
  shell: |
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  args:
    warn: no

- name: Add Kubernetes APT repository
  shell: |
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    warn: no
# - name: Get Kubernetes package key
#   become: true
#   ansible.builtin.shell: wget https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key #/tmp/kubernetes-release.key /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#     # dest: /tmp/kubernetes-release.key #/etc/apt/keyrings/kubernetes-apt-keyring.gpg

# - name: Move gpg key to path
#   shell: mv Release.key /tmp/kubernetes-release.key 

# - name: convert key to keyring
#   ansible.builtin.shell: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
#   args:
#     creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  
# - name: Add Kubernetes Repository using shell
#   ansible.builtin.shell: |
#     echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
#   args:
#     creates: /etc/apt/sources.list.d/kubernetes.list
####################################    
# - name: Add Kubernetes Repository
#   ansible.builtin.apt_repository:
#     repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /"
#     filename: kubernetes

# - name:  Get k8s pkg key
#   # ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#   ansible.builtin.shell: |
#     echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  # args:
  #   creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#################################################
# - name: Download Kubernetes public signing key
#   ansible.builtin.apt_key:
#     url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
#     dest: /etc/apt/keyrings/kubernetes-apt-keyring.key
#     mode: '0644'

# - name: Downloadkubernetes public signing key
#   command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg


# - name: Add Kubernetes APT repository
#   lineinfile:
#     path: /etc/apt/sources.list.d/kubernetes.list
#     line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /'
#     create: yes

# - name: Add Kubernetes Apt Key
#   # ansible.builtin.apt_key:
#   command: wget https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key -O /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    # keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  # state: present

# - name: Download APT Key
#   ansible.builtin.apt_key:
#     keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#     state: present
################################################
# - name: Add Kubernetes Repository
#   ansible.builtin.apt_repository:
#     repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /"
#     filename: kubernetes
    # state: present
#####################################################################
# - name: Download Kubernetes APT key
#   ansible.builtin.get_url:
#     url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
#     dest: /tmp/kubernetes-apt-key.key
#     mode: '0644'

# - name: Convert Kubernetes APT key to gpg format
#   ansible.builtin.command:
#     cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-key.key
#     args:
#     creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# - name: Add Kubernetes APT repository
#   ansible.builtin.lineinfile:
#     path: /etc/apt/sources.list.d/kubernetes.list
#     line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
#     create: yes
#################################################
# - name: Convert key to APT format
#   command: gpg --dearmor /etc/apt/keyrings/kubernetes-apt-keyring.key
#   args:
#       creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg



# - name: Download kubernetes repo and signing key
#   command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# - name: Download kubernetes repo
#   command: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install kubelet, kubectl, kubeadm
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - kubectl
    - kubeadm
    - kubelet
  
- name: Hold the any updates for kube components
  command: sudo apt-mark hold kubelet kubeadm kubectl
  notify: enable kubernetes



## Second Playbook
# ---
# - name: Disable swap
#   command: swapoff -a

# - name: Comment out swap in /etc/fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: '^/swap'
#     line: '#/swap'

# - name: Create .conf file to load modules at bootup
#   copy:
#     dest: /etc/modules-load.d/k8s.conf
#     content: |
#       overlay
#       br_netfilter
#     mode: '0644'

# - name: Load kernel modules
#   command: modprobe {{ item }}
#   with_items:
#     - overlay
#     - br_netfilter

# - name: Configure sysctl parameters
#   copy:
#     dest: /etc/sysctl.d/k8s.conf
#     content: |
#       net.bridge.bridge-nf-call-iptables  = 1
#       net.bridge.bridge-nf-call-ip6tables = 1
#       net.ipv4.ip_forward                 = 1
#     mode: '0644'

# - name: Apply sysctl parameters
#   command: sysctl --system

# - name: Update package repository
#   apt:
#     update_cache: yes

# - name: Install containerd
#   apt:
#     name: containerd
#     state: present

# - name: Ensure containerd service is running
#   service:
#     name: containerd
#     state: started
#     enabled: yes

# - name: Create containerd config directory
#   file:
#     path: /etc/containerd
#     state: directory

# - name: Generate default containerd configuration
#   command: containerd config default | tee /etc/containerd/config.toml
#   register: containerd_config
#   changed_when: false

# - name: Write containerd configuration
#   copy:
#     dest: /etc/containerd/config.toml
#     content: "{{ containerd_config.stdout }}"
#     mode: '0644'

# - name: Modify containerd config for systemd cgroups
#   lineinfile:
#     path: /etc/containerd/config.toml
#     regexp: '^SystemdCgroup'
#     line: 'SystemdCgroup = true'
#     state: present

# - name: Restart containerd service
#   service:
#     name: containerd
#     state: restarted

# - name: Install APT packages for Kubernetes repository
#   apt:
#     name:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - gpg
#     state: present

# - name: Create APT keyrings directory
#   file:
#     path: /etc/apt/keyrings
#     state: directory
#     mode: '0755'

# # - name: Fetch Kubernetes APT signing key
# #   shell: |
# #     curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
# #   register: key_fetch
# #   ignore_errors: yes
# - name: Add GPG Key
#   shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg


# # - name: Debug key fetching
# #   debug:
# #     msg: "{{ key_fetch }}"

# # - name: Add Kubernetes APT repository
# #   copy:
# #     dest: /etc/apt/sources.list.d/kubernetes.list
# #     content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
# #     mode: '0644'

# - name: Add k8s Repository
#   shell: cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
#     deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /
#     EOF


# # - name: Download Kubernetes APT signing key
# #   get_url:
# #     url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
# #     dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
# #     mode: '0644'

# # - name: Add Kubernetes APT repository
# #   copy:
# #     dest: /etc/apt/sources.list.d/kubernetes.list
# #     content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
# #     mode: '0644'

# - name: Update package index
#   apt:
#     update_cache: yes

# - name: Install kubelet, kubeadm, and kubectl
#   apt:
#     name:
#       - kubelet
#       - kubeadm
#       - kubectl
#     state: present

# - name: Pin kubelet, kubeadm, and kubectl versions
#   apt:
#     name:
#       - kubelet
#       - kubeadm
#       - kubectl
#     state: held

# - name: Enable kubelet service
#   service:
#     name: kubelet
#     state: started
#     enabled: yes