FROM postgres:latest


# To run this psql container we have to pass credential of this databse
# Like Db user , DB password & DB name. 
# We will use ENV for same

ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydatabase