pipeline {
    agent any 
    //   tools {
    //     maven 'maven-3.9.0'
    //   }

    stages{
        stage('Checkout') {
            steps {
                git branch: 'training', url: 'https://github.com/GitEic-Bhavin/35_Days_Training_repo.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh 'docker build -t bhavin1099/jenkins-app-java:v2 -f Project/Day14/Dockerfile .'                       
                 }
            
                    
                }
            } 
        }
        stage('Push') {
          steps {
              script {
                  withDockerRegistry(credentialsId: 'docker-cred') {
                    sh 'docker push bhavin1099/jenkins-app-java:v2'
                  }    
              }
            }
        }

        stage('Deploy Container'){
            steps{
                script{
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        def runContainer = docker.image("bhavin1099/jenkins-app-java:v2").run('--name mynew-container -d')
                        
                    }
                }
            }
        }
    }
}